// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Digit: typeof import('./src/components/Digit.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Function: typeof import('./src/components/Function.vue')['default']
    Keys: typeof import('./src/components/Keys.vue')['default']
    Plate: typeof import('./src/components/Plate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
